---
title: "MCF10A cells in LI_I_L_035_01_1"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

Exploration of segmentation, tracking and processing of MCF10A cells using Fiji for registration and ilastik for pixel classification, segmentation, tracking and analysis.


```{r "setup", include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE,
                      cache=FALSE)
library(tidyverse)
library(RColorBrewer)
library(gplots)
library(scales)
library(tiff)
library(EBImage)


#Setup colors
spectralPal <- brewer.pal(11,"Spectral")[11:1]


```

```{r get_data, cache.lazy = TRUE}

#Read in a CSV with ilastik tracking data
data_path <- "/eppec/storage/groups/heiserlab/image_scratch/"
nuclear_dir_name <- "R_Reg"
reporter_dir_name <- "G_Reg"
phase_dir_name <- "P_Reg"
barcode <- "LI_I_L_035_01_1"

#Filter thresholds
max_nuclear_diff <- 100
min_nuclear_diff <- -100
max_reporter_diff <- 100
min_reporter_diff <- -100
max_nuclear_dis <- 10000
max_Size_in_pixels_0_nuclear <- 22500
max_Size_in_pixels_1_nuclear <- 22500


well_location_dirs <- dir(paste0(data_path, barcode), pattern = "[[:alnum:]]*_[[:digit:]]*", full.names = TRUE)[c(1,3,4)]
#Get the nuclear data
raw_data <- lapply(well_location_dirs, function(well_location_dir){
  phase_data_filename <- dir(paste0(well_location_dir,"/",phase_dir_name),pattern = "CSV-Table", full.names = TRUE)
  if(is_empty(phase_data_filename)) stop("No phase data found in ", well_location_dir)
  all_data <- read_csv(phase_data_filename) %>%
    mutate(Location = str_remove(well_location_dir, ".*/"),
           Well = str_remove(Location,"_.*"),
           Location_trackId = str_c(Location,  "_", trackId))
  # #Get the reporter data for the same image location
  # reporter_data_filename <- dir(paste0(well_location_dir,"/",reporter_dir_name),pattern = "CSV-Table", full.names = TRUE)
  # if(is_empty(reporter_data_filename)) stop("No reporter data found in ", well_location_dir)
  # reporter_cell_data <- read_csv(reporter_data_filename)
  # 
  #Get and add the GFP background data
  #reporter_background_data_filename <- dir(paste0(well_location_dir,"/",reporter_dir_name),pattern = "background", full.names = TRUE)
 # reporter_data <- read_csv(reporter_background_data_filename) %>%
    # mutate(frame = 0:(n()-1)) %>%
    # select(frame, Background_median) %>%
    # right_join(reporter_cell_data) %>%
    # mutate(Mean_Intensity_0_raw_reporter = Mean_Intensity_0,
    #        Mean_Intensity_0 = Mean_Intensity_0_raw_reporter - Background_median*2^16)
  
  # all_data <- nuclear_data %>%
  #   inner_join(reporter_cell_data, by=c("frame", "Center_of_the_object_0", "Center_of_the_object_1"))
  # missing_nuclear_data <- nuclear_data %>%
  #   anti_join(all_data, by=c("frame", "Center_of_the_object_0", "Center_of_the_object_1"))
  #   missing_reporter_data <- reporter_data %>%
  # #   anti_join(all_data, by=c("frame", "Center_of_the_object_0", "Center_of_the_object_1"))
   colnames(all_data)[str_detect(colnames(all_data),"_[[:digit:]]")] <- str_c(colnames(all_data)[str_detect(colnames(all_data),"_[[:digit:]]")], "_nuclear")
   
  # colnames(all_data) <- str_replace_all(colnames(all_data), "[.]y","_reporter")
  
return(all_data)
}) %>%
  bind_rows()

#addmetadata
raw_data_metadata <- read_csv(paste0(data_path,"/",barcode,"/Analysis/",barcode,"_exp_metadata.csv")) %>%
  select(matches("Well|CellLine-1$|Drug|Ligand|Reporter|Image")) %>%
  distinct() %>%
  right_join(raw_data, by=c("Well"))

colnames(raw_data_metadata)[str_detect(colnames(raw_data_metadata),"-")] <- str_replace_all(colnames(raw_data_metadata)[str_detect(colnames(raw_data_metadata),"-")], "-","_")
raw_data_metadata <- mutate(raw_data_metadata, Time = frame*Image_period)

first_valid_frame <- 1

processing1 <- raw_data_metadata %>%
  filter(lineageId > 1,
         trackId > 1,
         frame >= first_valid_frame) %>% #limit to valid tracks, lineages and microscope ready data 
  group_by(Location_trackId) %>%
  mutate(Track_length = n()) %>%
  ungroup() %>% 
  #remove dividing, disappearing and appearing cells
  filter(Track_length==max(length(unique(frame)))) %>% 
  group_by(Location_trackId) %>%
  mutate(Mean_Intensity_0_nuclear_sum = sum(Mean_Intensity_0_nuclear),
         Mean_Intensity_0_nuclear_T0 = Mean_Intensity_0_nuclear[frame==first_valid_frame],
         Mean_Intensity_0_nuclear_T0norm = Mean_Intensity_0_nuclear/Mean_Intensity_0_nuclear_T0,
         Mean_Intensity_0_nuclear_T0norm_sum = sum(Mean_Intensity_0_nuclear_T0norm)) %>%
  mutate(Mean_Intensity_1_nuclear_sum = sum(Mean_Intensity_1_nuclear),
    Mean_Intensity_1_nuclear_T0 = Mean_Intensity_1_nuclear[frame==first_valid_frame],
    Mean_Intensity_1_nuclear_T0norm = Mean_Intensity_1_nuclear/Mean_Intensity_1_nuclear_T0,
    Mean_Intensity_1_nuclear_T0norm_sum = sum(Mean_Intensity_1_nuclear_T0norm),
         Movement_0_nuclear = c(diff(Object_Center_0_nuclear),0),
         Movement_1_nuclear = c(diff(Object_Center_1_nuclear),0),
         Distance_01_nuclear = sqrt(Movement_0_nuclear^2 + Movement_1_nuclear^2),
         Mean_Intensity_0_nuclear_T0norm_diff =  c(diff(Mean_Intensity_0_nuclear_T0norm),0),
         Mean_Intensity_1_nuclear_T0norm_diff = c(diff(Mean_Intensity_1_nuclear_T0norm),0),
         Size_in_pixels_0_nuclear_diff = c(diff(Size_in_pixels_0_nuclear),0)) %>%
  ungroup()

pr_data_metadata <- raw_data_metadata %>%
  filter(lineageId > 1,
         trackId > 1,
         frame >= first_valid_frame) %>% #limit to valid tracks, lineages and microscope ready data 
  group_by(Location_trackId) %>%
  mutate(Track_length = n()) %>%
  ungroup()

```


####lineage information
There are five in features in the ilastik tracking data. A summary of all values and a few rows of these values are:

```{r ilastikIds}
df <- pr_data_metadata %>%
  select(matches("Id",ignore.case = FALSE),
         -Location_trackId)

summary(df)

df %>%
  top_n(100)
```


```{r exploreIDvalues}

p <- ggplot(pr_data_metadata, aes(x=Time, y=trackId, group=trackId)) +
  geom_line(alpha = .5)
p

p <- ggplot(pr_data_metadata, aes(x=Time, y=lineageId, group=trackId)) +
  geom_line(alpha = .5)
p


p <- ggplot(pr_data_metadata, aes(x=Time, y=lineageId, colour=trackId)) +
  geom_point(alpha = .5) +
  geom_jitter(height = .4, width=0)
p
```
```{r countCells}
df <- pr_data_metadata %>%
  group_by(Time, Location) %>%
  count()

p <- ggplot(df, aes(x = Time, y = n)) +
  geom_path() +
  facet_grid(~Location)
p

```
