---
title: "AU565 drug combination responses"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(RColorBrewer)

```


```{r get_data}

raw_data <- dir("../data", pattern = "_level_0",full.names = TRUE) %>%
  map(read_csv, progress = FALSE,
      col_types = cols(
  X1 = col_double(),
  label = col_double(),
  Nuclei_CL_NR_area = col_double(),
  Nuclei_CL_NR_eccentricity = col_double(),
  Nuclei_CL_NR_mean_intensity = col_double(),
  Nuclei_CL_NR_max_intensity = col_double(),
  Nuclei_CL_NR_min_intensity = col_double(),
  Nuclei_CL_NR_feret_diameter_max = col_double(),
  Nuclei_CL_NR_solidity = col_double(),
  well = col_character(),
  field = col_double(),
  time = col_character(),
  label_1 = col_double(),
  Nuclei_CL_CC_mean_intensity = col_double(),
  Nuclei_CL_CC_max_intensity = col_double(),
  Nuclei_CL_CC_min_intensity = col_double()
)) %>%
  bind_rows() %>%
  mutate(well_col = str_remove(well, "[A-Z]"),
         well_col = as.integer(well_col),
         well = sprintf("%.1s%02.2d", well, well_col),
         day = str_remove(time, "d.*"),
         day = as.integer(day),
         hour = str_extract(time, "[0-9]*h"),
         hour = str_remove(hour, "h"),
         hour = as.integer(hour),
         minute = str_extract(time, "[0-9]*m"),
         minute = str_remove(minute, "m"),
         minute = as.integer(minute),
         elapsed_minutes = day*24*60+hour*60+minute) %>%
  filter(!elapsed_minutes %in% c()) %>%
  drop_na()

```

```{r get_and_merge_metadata}

metadata <- dir(path = "../metadata/", pattern = "xlsx", full.names = TRUE)  %>%
  map(readxl::read_excel) %>%
  bind_rows() %>%
  mutate(ligand = paste(Ligand1, Ligand2, Ligand3, sep = "_"),
         ligand = str_remove_all(ligand, "_none"),
         drugs =  paste(Drug1 ,Drug2, sep = "_"),
         drugs = str_remove_all(drugs, "_none|_0"),
         treatment =  paste(Drug1, Drug1Concentration,Drug2, Drug2Concentration, sep = "_"),
         treatment = str_remove_all(treatment, "_none|_0")) %>%
  distinct()

data_ann <- raw_data %>%
  left_join(metadata, by = c("well" = "Well")) 

```


perform a quick check on four fields from each well.

```{r visualize_data, fig.width= 10, fig.height=14}
field_data <- data_ann %>%
  group_by(well, field, elapsed_minutes, treatment, drugs, Drug1,
           Drug1Concentration, Drug2, Drug2Concentration) %>%
  summarise(n = n(),
            Nuclei_CL_NR_mean_intensity = mean(Nuclei_CL_NR_mean_intensity),
            Nuclei_CL_CC_mean_intensity=mean(Nuclei_CL_CC_mean_intensity),
            Cyto_CL_CC_mean_intensity=mean(Cyto_CL_CC_mean_intensity),
            Cell_CL_CC_mean_intensity_ratio=mean(Cell_CL_CC_mean_intensity_ratio),
            Cell_CL_CC_max_intensity_ratio=mean(Cell_CL_CC_max_intensity_ratio),
            Cell_CL_CC_min_intensity_ratio=mean(Cell_CL_CC_min_intensity_ratio),
            .groups = "drop")

p_n <- ggplot(field_data, aes(x = elapsed_minutes, y = n, color = factor(field))) +
  geom_path() +
  labs(title = "Cell counts in each field",
       xlab ="minutes",
       ylab = "cell count") +
  facet_wrap(~well, ncol = 6)
p_n


p_n_t <- ggplot(field_data, aes(x = elapsed_minutes, y = n, color = treatment, group = interaction(field, well))) +
  geom_path() +
  labs(title = "Cell counts for each treatment",
       xlab ="minutes",
       ylab = "cell count") +
  guides(color = guide_legend(ncol = 1)) +
  facet_wrap(~treatment, ncol = 6)+
  theme(strip.text = element_text(size = 5))
p_n_t

p_NR <- ggplot(field_data, aes(x = elapsed_minutes, y = Nuclei_CL_NR_mean_intensity, color = factor(field))) +
  geom_path() +
  labs(title = "Nuclear reporter intensity, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~well, ncol = 2)
p_NR

p_CC <- ggplot(field_data, aes(x = elapsed_minutes, y = Nuclei_CL_CC_mean_intensity, color = factor(field))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the nuclei, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~well, ncol = 6)
p_CC

p_CC_t <- ggplot(field_data, aes(x = elapsed_minutes, y = Nuclei_CL_CC_mean_intensity, color = treatment, group = interaction(field, well))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the nuclei, mean",
       xlab = "minutes",
       ylab = "intensity") +
    guides(color = guide_legend(ncol = 1)) +
  facet_wrap(~treatment, ncol = 2)
p_CC_t


p_cyto_CC <- ggplot(field_data, aes(x = elapsed_minutes, y = Cyto_CL_CC_mean_intensity, color = factor(field))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the cytoplasm, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~well, ncol = 6)
p_cyto_CC

p_cyto_CC_t <- ggplot(field_data, aes(x = elapsed_minutes, y = Cyto_CL_CC_mean_intensity, color = treatment, group = interaction(field, well))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the cytoplasm, mean",
       xlab = "minutes",
       ylab = "intensity") +
      guides(color = guide_legend(ncol = 1)) +
  facet_wrap(~treatment, ncol = 6)+
  theme(strip.text = element_text(size = 5))
p_cyto_CC_t

p_cyto_CC_ratio <- ggplot(field_data, aes(x = elapsed_minutes, y = Cell_CL_CC_mean_intensity_ratio, color = factor(field))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the cytoplasm/nuclei, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~well, ncol = 2)
p_cyto_CC_ratio

p_cyto_CC_t_ratio <- ggplot(field_data, aes(x = elapsed_minutes, y = Cell_CL_CC_mean_intensity_ratio, color = treatment, group = interaction(field, well))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the cytoplasm/nuclei, mean",
       xlab = "minutes",
       ylab = "intensity") +
    guides(color = guide_legend(ncol = 1)) +
  facet_wrap(~treatment, ncol = 2)
p_cyto_CC_t_ratio

# p_n_ds <- ggplot(field_data, aes(x = elapsed_minutes, y = n, color = interaction(Drug1Concentration, Drug2Concentration), group = drugs)) +
#   geom_path() +
#   labs(title = "Cell counts for each treatment",
#        xlab ="minutes",
#        ylab = "cell count") +
#   guides(color = guide_legend(ncol = 1)) +
#   facet_wrap(~drugs, ncol = 6)+
#   theme(strip.text = element_text(size = 5))
# p_n_ds

pdf("../plots/AU565_cell_counts_intensities.pdf", width = 10, height = 14)
p_n
p_n_t
p_CC
p_CC_t
p_NR
p_cyto_CC
p_cyto_CC_t
p_cyto_CC_ratio
p_cyto_CC_t_ratio
res <- dev.off()

```
