---
title: "MCF10A live cell image analysis"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(RColorBrewer)

create_pdfs <- TRUE

```

```{r}

df_input <- dir("Data", pattern = "LI802303.*_lineages.csv$", full.names = TRUE)%>%
  map(read_csv,
      col_types = cols(
        .default = col_double(),
        D2Rpixel = col_logical(),
        field = col_character(),
        well = col_character(),
        treatment = col_character()
      )) %>%
  map(tibble) %>%
  bind_rows() %>%
  mutate(well_field = paste0(well, "_",field),
         thour = tmin/60)

```


```{r TIDdistributions, fig.width=3, fig.height=3}

#count and display the number of cells in each lineage
df <- df_input %>%
  select(TID, field, well, treatment) %>%
  distinct() 

p <- ggplot(df, aes(x = treatment)) +
  geom_bar() +
  labs(title = "Count of cells in dataset") +
  theme(axis.text.x = element_text(angle = 90))
p

#count and display the number of lineages in each lineage

df <- df_input %>%
  select(lineage, field, well, treatment) %>%
  distinct() 

p <- ggplot(df, aes(x = treatment)) +
  geom_bar() +
  labs(title = "Count of lineages in dataset") +
  theme(axis.text.x = element_text(angle = 90))
p

df <- df_input %>%
  select(TID, lineage, field, well, treatment, distance_mean) %>%
  group_by(treatment) %>%
  summarise(distance_mean = mean(distance_mean, na.rm = TRUE)) %>%
  ungroup()

p <- ggplot(df, aes(x = treatment, y = distance_mean)) +
  geom_col() +
  labs(title = "Average cell movement",
       subtitle = "(per 30 minute time period)",
       y = "distance(pixels)") +
  theme(axis.text.x = element_text(angle = 90))
p

```


```{r migration_across_time, fig.width=8, fig.height=5}

df <- df_input %>%
  group_by(treatment, thour) %>%
  summarise(distance = mean(distance)) %>%
  ungroup()

p <- ggplot(df, aes(x = thour, y = distance, colour = treatment)) +
  geom_path(size = .8, alpha = .6) +
  geom_point(size = .8, alpha = .4)+
  geom_smooth(method = "loess", formula = 'y ~ x', alpha = .8, se = FALSE
  )+
  coord_cartesian(xlim = c(0,48)) +
  scale_x_continuous(breaks = c(0,12,24,36,48)) +
  labs(title = "Migration distance over time",
       x = "time (hours)",
       y = "distance moved (pixels)") +
  theme_bw()
p

if(create_pdfs){
  pdf("MDD_migration_distance_summarized.pdf", useDingbats = FALSE, width = 8, height = 5)
  print(p)
  res <- dev.off()
}

```

```{r migration_facets, fig.width=8, fig.height=7}

df <- df_input %>%
  group_by(treatment, thour, well, field) %>%
  summarise(distance = mean(distance)) %>%
  ungroup()

p <- ggplot(df, aes(x = thour, y = distance, colour = treatment, group = field)) +
  geom_path(size = .4, alpha = .8) +
  geom_point(size = .4, alpha = .4)+
  geom_smooth(method = "loess", formula = 'y ~ x', alpha = .8, se = FALSE
  )+
  coord_cartesian(xlim = c(0,48),
                  ylim = c(0,35)) +
  scale_x_continuous(breaks = c(0,12,24,36,48)) +
  labs(title = "Migration distance over time",
       x = "time (minutes)",
       y = "distance moved (pixels)") +
  theme_bw() +
  facet_wrap(~treatment, ncol = 4)
p

if(create_pdfs){
  pdf("MDD_migration_distance.pdf", useDingbats = FALSE, width = 8, height = 4)
  print(p)
  res <- dev.off()
}

```



```{r plot_migration, fig.width=6, fig.height=8}

cols <- RColorBrewer::brewer.pal(9, name = "Set1")[sample(1:9, length(unique(df_input$TID)), replace = TRUE)]

p <- ggplot(df_input, aes(xpixel, ypixel, colour = factor(TID))) +
  geom_point(size = .1, alpha = .8) +
  geom_path(size = .1, alpha = .8) +
  scale_colour_manual(values = cols) +
  guides(colour = FALSE) +
  labs(title = "absolute positions, all data") +
  theme_bw() +
  theme(strip.text = element_text(size = 5, margin = margin()),
        strip.background = element_rect(fill = "transparent")) +
  facet_wrap(~well+field+treatment)
p

```


```{r relative_migration, fig.width=8, fig.height=8}

T0_rel <- df_input %>%
  filter(PID == 1) %>%
  select(well, field, TID, xpixel, ypixel) %>%
  rename(x_T0_rel = xpixel,
         y_T0_rel = ypixel) %>%
  right_join(df_input, by = c("TID", "well", "field") )%>%
  mutate(x_rel = xpixel-x_T0_rel,
         y_rel = ypixel-y_T0_rel) %>%
  select(x_rel, y_rel, TID, well, field, treatment, lineage, generation, tmin) %>%
  drop_na()

cols <- RColorBrewer::brewer.pal(9, name = "Set1")[sample(1:9, length(unique(T0_rel$TID)), replace = TRUE)]

p <- ggplot(T0_rel, aes(x_rel, y_rel, colour = factor(TID))) +
  geom_point(size = .1, alpha = .8) +
  geom_path(size = .1, alpha = .8) +
  scale_colour_manual(values = cols) +
  guides(colour = FALSE) +
    labs(title = "relative tracks",
         subtitle = "all tracks start at the origin")+
  theme_bw()+
    theme(strip.text = element_text(size = 5, margin = margin()),
        strip.background = element_rect(fill = "transparent")) +
facet_wrap(~well+field+treatment)
p
```

```{r relative_migration_linked, fig.width=8, fig.height=5}
#balance the number of lineages in each treatment
min_treatment_lineages <- T0_rel %>%
  select(treatment, lineage, generation) %>%
  filter(generation == 1) %>%
  distinct() %>%
  count(treatment) %>%
  pull() %>%
  min()

set.seed(42)
lineages <- T0_rel %>%
  select(treatment, lineage, well, field, generation) %>%
    filter(generation == 1) %>%
  distinct() %>%
  group_by(treatment) %>%
  sample_n(size = min_treatment_lineages, replace = FALSE) %>%
  ungroup() %>%
  mutate(key = paste0(well, "_", field, "_", lineage))


#select one daughter at each generation
single_daughter_data <- df_input %>%
  mutate(key = paste0(well, "_",field, "_", lineage)) %>%
  filter(key %in% lineages$key) %>%
  select(TID, generation, key, treatment, lineage, tmin, xpixel, ypixel) %>%
  distinct() %>%
  group_by(key, lineage, tmin) %>%
  arrange(generation, TID) %>%
  slice_head(n = 1) %>%
  ungroup()

single_daughter_TIDs <- single_daughter_data %>%
  select(key, treatment, lineage, generation, TID) %>%
  distinct()

#link daughters to mothers and move all lineages to start at origin
df_gen1_T0_rel <-  T0_rel %>%
    mutate(key = paste0(well, "_",field, "_", lineage)) %>%
  right_join(single_daughter_TIDs, by = c("TID", "generation", "key", "lineage", "treatment")) %>%
  filter(generation == 1)

df_daughters <- df_input  %>%
    mutate(key = paste0(well, "_",field, "_", lineage)) %>%
  right_join(single_daughter_TIDs, by = c("TID", "generation", "key", "lineage", "treatment"))  %>%
  filter(!generation == 1) 

df_daughters_gen1_rel <-  df_input %>%
    mutate(key = paste0(well, "_",field, "_", lineage)) %>%
  right_join(single_daughter_TIDs, by = c("TID", "generation", "key", "lineage", "treatment")) %>%
  filter(generation == 1,
         PID == 1) %>%
   rename(x_T0 = xpixel,
         y_T0 = ypixel) %>%
  select(well, field, lineage, x_T0, y_T0) %>%
  right_join(df_daughters, by = c("lineage", "well", "field")) %>%
  mutate(x_rel = xpixel-x_T0,
         y_rel = ypixel-y_T0) %>%
  select(x_rel, y_rel, TID, key, well, field, treatment, lineage, generation, tmin) %>%
  drop_na()

df <- df_daughters_gen1_rel %>%
  select(key, well, field, TID, treatment, lineage, generation, tmin, x_rel, y_rel) %>%
  bind_rows(df_gen1_T0_rel)

p <- ggplot(df, aes(x = tmin, y = key)) +
  geom_point(size = 1.2) +
  labs(title = "Lineages vs time to show missing data") +
  theme_bw()+
  theme(axis.text.y = element_text(size = 4))

p

p <- ggplot(df, aes(x_rel, y_rel, colour = factor(lineage))) +
  geom_path(size = .4, alpha = .8) +
  scale_colour_manual(values = cols) +
  guides(colour = FALSE) +
  labs(title = "Relative motion of equal number of lineages")+
  theme_bw()+
  theme(strip.text = element_text(size = 12),
        strip.background = element_rect(fill = "transparent"),
        axis.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line =element_blank()) +
  facet_wrap(~treatment, ncol = 4)
p

if(create_pdfs){
  pdf("MDD_migration_relative_tracks.pdf", useDingbats = FALSE, width = 8, height = 5)
  print(p)
  res <- dev.off()
}


```

