---
title: "MCF10A ligand cmbinations"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(RColorBrewer)

```


```{r get_data, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}

raw_data <- dir("tables", pattern = "_level_0",full.names = TRUE) %>%
  map(read_csv, progress = FALSE,
      col_types = cols(
  X1 = col_double(),
  label = col_double(),
  Nuclei_CL_NR_area = col_double(),
  Nuclei_CL_NR_eccentricity = col_double(),
  Nuclei_CL_NR_mean_intensity = col_double(),
  Nuclei_CL_NR_max_intensity = col_double(),
  Nuclei_CL_NR_min_intensity = col_double(),
  Nuclei_CL_NR_feret_diameter_max = col_double(),
  Nuclei_CL_NR_solidity = col_double(),
  well = col_character(),
  field = col_double(),
  time = col_character(),
  label_1 = col_double(),
  Nuclei_CL_CC_mean_intensity = col_double(),
  Nuclei_CL_CC_max_intensity = col_double(),
  Nuclei_CL_CC_min_intensity = col_double()
)) %>%
  bind_rows() %>%
  mutate(well_col = str_remove(well, "[A-Z]"),
         well_col = as.integer(well_col),
         well = sprintf("%.1s%02.2d", well, well_col),
         day = str_remove(time, "d.*"),
         day = as.integer(day),
         hour = str_extract(time, "[0-9]*h"),
         hour = str_remove(hour, "h"),
         hour = as.integer(hour),
         minute = str_extract(time, "[0-9]*m"),
         minute = str_remove(minute, "m"),
         minute = as.integer(minute),
         elapsed_minutes = day*24*60+hour*60+minute) %>%
  filter(!elapsed_minutes %in% c(45, 150, 810, 1050, 1185, 1575, 2100))

```

```{r get_and_merge_metadata}

metadata <- dir("metadata/", pattern = "xlsx", full.names = TRUE)  %>%
  readxl::read_excel() %>%
  mutate(treatment = paste(Ligand1, Ligand2, Ligand3, sep = "_"),
         treatment = str_remove_all(treatment, "_none"))

data_ann <- raw_data %>%
  left_join(metadata, by = c("well" = "Well")) 

```


perform a quick check on four fields from each well.

```{r visualize_data, fig.height=8}
field_data <- data_ann %>%
  group_by(well, field, elapsed_minutes, treatment) %>%
  summarise(n = n(),
            Nuclei_CL_NR_mean_intensity = mean(Nuclei_CL_NR_mean_intensity),
            Nuclei_CL_CC_mean_intensity=mean(Nuclei_CL_CC_mean_intensity), .groups = "drop")

p_n <- ggplot(field_data, aes(x = elapsed_minutes, y = n, color = factor(field))) +
  geom_path() +
  labs(title = "Cell counts in each field",
       xlab ="minutes",
       ylab = "cell count") +
  facet_wrap(~well, ncol = 2)
p_n


p_n_t <- ggplot(field_data, aes(x = elapsed_minutes, y = n, color = treatment, group = interaction(field, well))) +
  geom_path() +
  labs(title = "Cell counts for each treatment",
       xlab ="minutes",
       ylab = "cell count") +
  facet_wrap(~treatment, ncol = 2)
p_n_t

p_NR <- ggplot(field_data, aes(x = elapsed_minutes, y = Nuclei_CL_NR_mean_intensity, color = factor(field))) +
  geom_path() +
  labs(title = "Nuclear reporter intensity, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~well, ncol = 2)
p_NR

p_CC <- ggplot(field_data, aes(x = elapsed_minutes, y = Nuclei_CL_CC_mean_intensity, color = factor(field))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the nuclei, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~well, ncol = 2)
p_CC


p_CC_t <- ggplot(field_data, aes(x = elapsed_minutes, y = Nuclei_CL_CC_mean_intensity, color = treatment, group = interaction(field, well))) +
  geom_path() +
   labs(title = "Cell cycle intensity in the nuclei, mean",
       xlab = "minutes",
       ylab = "intensity") +
  facet_wrap(~treatment, ncol = 2)
p_CC_t

pdf("LI204601_cell_counts_intensities.pdf")
p_n
p_n_t
p_CC
p_CC_t
p_NR
res <- dev.off()
```
