---
title: "Live cell imaging field-level responses"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(viridis)
library(readxl)

```


```{r get_data}
get_QA_data <- function(plateID){
  filename <- paste0(data_path, plateID,"/Analysis/",pipeline_name,"/",plateID,"_QA_evaluation.csv")
  if(file.exists(filename)){
    df <- read_csv(filename,
                   col_types = cols(
                     plateID = col_character())) %>%
      select(plateID, well, field)
  } else{
    return(NULL)
  }
  return(df)
}

create_level_2_data <- function(plateID, data_path = "/home/exacloud/gscratch/HeiserLab/images/", pipeline_name = "CKtnK"){
  l2_data_path <- paste0(data_path,plateID,"/Analysis/",pipeline_name,"/",plateID,"_level_2.csv")

  print(paste("creating new level 2 file for",plateID))
  l2 <- map_dfr(dir(paste0(data_path,plateID,"/Analysis/",pipeline_name),pattern = paste0(plateID,"_.*_level_2.csv"), full.names = TRUE), read_csv, show_col_types = FALSE,
                col_types =cols(.default = "d",
                                plateID = col_character(),
                                well = col_character(),
                                field = col_character(),
                                time_slice = col_character(),
                                Drug1 = col_character(),
                                #Drug1Concentration = col_character(),
                                Drug2 = col_character(),
                                #Drug2Concentration = col_character(),
                                treatment = col_character())) %>%
    mutate(drugs =  paste(Drug1 ,Drug2, sep = "_"),
           drugs = str_remove_all(drugs, "_none|_0$"),
           treatment = str_remove_all(treatment, "_none"),
           treatment = str_remove_all(treatment, "_0$"),
           hours = elapsed_minutes/60) 
  # %>%
  #   filter(!elapsed_minutes %in% c(0, 30, 60, 90, 120, 150, 180, 210, 240)) 
  
  #normalize to earliest time points
  
  earliest_time_points <- sort(unique(l2$elapsed_minutes))[1:2]
    # earliest_time_point <- unique(l2$elapsed_minutes) %>%
    #   min()
    
    l2 <- l2 %>%
      filter(elapsed_minutes %in% earliest_time_points) %>%
      group_by(plateID, well, field) %>%
      mutate(n_0 = mean(n)) %>%
      ungroup() %>%
      select("plateID","well", "field", "n_0") %>%
      right_join(l2,by = c("plateID", "well", "field")) %>%
      mutate(cell_count_norm_T0 = n/n_0)
    

    l2 <- l2 %>%
      select(Drug1, Drug1Concentration) %>%
      unique() %>%
      group_by(Drug1) %>%
      mutate(Drug1ConcentrationRank = rank(Drug1Concentration),
             Drug1ConcentrationRank = as.character(Drug1ConcentrationRank),
             Drug1ConcentrationRank = factor(Drug1ConcentrationRank, levels = c("1", "2", "3", "4", "5", "6", "7"), ordered = TRUE)) %>%
    right_join(l2, by = c("Drug1", "Drug1Concentration"))
    
    write_csv(l2,l2_data_path)

  return(l2)
}

generate_l2_plots <- function(plateID){
  l2_data_path <- paste0(data_path,plateID,"/Analysis/",pipeline_name,"/",plateID,"_level_2.csv")
  
  df <- datasets[[plateID]] %>%
    mutate(field = as.factor(field)) %>% 
    arrange(elapsed_minutes)
  
    #dynamically assign consistent colors to the dosage concentrations
  treatments <-df$treatment%>%
    unique()  %>%
    str_sort(numeric = TRUE)
  idx <- which(treatments %in% c("control","vehicle","Untreated")) # Positions of Untreated in df$treatment
  treatments <- treatments[-idx]
  treatments_colors <-  rep(viridis(7, direction = -1), length.out = length(treatments))
  names(treatments_colors) <- treatments
  cols <- c("control"="royalblue","vehicle"="royalblue","Untreated"="royalblue", treatments_colors)
  
  p_n <- ggplot(df, aes(x = hours, y = n, color = field, group = field)) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
    scale_y_continuous(trans = 'log2')+
    scale_x_continuous(breaks = c(0,24,48,72,96)) +
    labs(title = "Cell counts in each field",
         subtitle = "organized by position in the plate") +
    xlab("hours") +
    ylab("cell count (log2 spacing)") +
    facet_wrap(~well, ncol = 6)
  p_n
  
  p_n_T0 <- ggplot(df, aes(x = hours, y = cell_count_norm_T0, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
        scale_x_continuous(breaks = c(0,24,48,72,96)) +
    scale_y_continuous(trans = 'log2') +
    labs(title = "Cell counts in each field (T0 normed)",
         subtitle = "organized by position in the plate") +
         xlab("hours") +
         ylab("cell count (log2 spacing)") +
    facet_wrap(~well, ncol = 6)
  p_n_T0
  
  # p_CC <- ggplot(df, aes(x = elapsed_minutes, y = Nuclei_CtnK_CC_mean_intensity, color = factor(field))) +
  #   geom_path() +
  #   stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
  #   labs(title = "Cell cycle intensity in the nuclei, mean") +
  #        xlab("minutes") +
  #        ylab("intensity") +
  #   facet_wrap(~well, ncol = 6)
  # p_CC
  # 

  # p_cyto_CC <- ggplot(df, aes(x = elapsed_minutes, y = Cyto_CtnK_CC_mean_intensity, color = factor(field))) +
  #   geom_path() +
  #   stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
  #   labs(title = "Cell cycle intensity in the cytoplasm, mean") +
  #        xlab("minutes") +
  #        ylab("intensity") +
  #   facet_wrap(~well, ncol = 6)
  # p_cyto_CC
  
  p_cyto_CC_ratio <- ggplot(df, aes(x = hours, y = Cell_CtnK_CC_mean_intensity_ratio, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
        scale_x_continuous(breaks = c(0,24,48,72,96)) +
    labs(title = "Cell cycle intensity in the cytoplasm/nuclei, mean") +
         xlab("hours") +
         ylab("intensity") +
    facet_wrap(~well, ncol = 2)
  p_cyto_CC_ratio
  
  #summarize each well and group plots by drug
  df_control_mean <- df %>%
    filter(treatment %in% c("vehicle", "control", "Untreated")) %>%
    group_by(elapsed_minutes) %>%
    summarise(cell_count_norm_T0_control = mean(cell_count_norm_T0),
              n_control = mean(n),
              G1_proportion_control = mean(G1_proportion),
               .groups = "drop")
  
  df_mean <- df %>%
    filter(!treatment %in% c("vehicle", "control", "Untreated")) %>%
    mutate(treatment = fct_drop(treatment)) %>%
    group_by(elapsed_minutes, treatment, drugs, Drug1Concentration,Drug1ConcentrationRank) %>%
    summarise(cell_count_norm_T0 = mean(cell_count_norm_T0),
              n = mean(n),
              G1_proportion = mean(G1_proportion), .groups = "drop") %>%
    left_join(df_control_mean, by = "elapsed_minutes")%>%
    mutate(hours = as.integer(elapsed_minutes)/60,
           hours = as.character(hours),
           hours = fct_inseq(hours, ordered = TRUE),
           cell_count_norm_control = n/n_control)
  
  df_mean_select <- df_mean %>%
    filter(hours %in% c(0, 24, 48, 72, 96)) %>%
    arrange(drugs, Drug1ConcentrationRank)
  
  drug1_concentration_ranks <- unique(df_mean_select$Drug1ConcentrationRank)
  rank_colors <-  rep(viridis(7, direction = -1), length.out = length(drug1_concentration_ranks))
  
  
  p_n_t_T0_mean <- ggplot(df_mean, aes(x = hours, y = cell_count_norm_T0, color = treatment, group = Drug1Concentration)) +
    geom_path() +
    geom_path(aes(y = cell_count_norm_T0_control), color = "firebrick4")+
    scale_x_discrete(breaks = c(0,24,48,72,96)) +
    scale_y_continuous(trans = 'log2') +
    scale_color_manual(values = cols) +
    labs(title = "Cell counts for each treatment (T0 normed)",
         subtitle = "organized by treatment and dosage") +
    xlab("hours") +
    ylab("cell count (log2 spacing)") +
    guides(color = "none") +
    facet_wrap(~drugs, ncol = 6)+
    theme(strip.text = element_text(size = 5)) +
    theme_bw()
  p_n_t_T0_mean
  
  p_G1_t_mean <- ggplot(df_mean, aes(x = hours, y = G1_proportion, color = treatment, group = Drug1Concentration)) +
    geom_path() +
    geom_path(aes(y = G1_proportion_control), color = "firebrick4")+
    scale_x_discrete(breaks = c(0,24,48,72,96)) +
    scale_color_manual(values = cols) +
    labs(title = "G1 proportion for each treatment",
         subtitle = "organized by treatment and dosage") +
         xlab("hours") +
         ylab("G1 proportion") +
    guides(color = "none") +
    facet_wrap(~drugs, ncol = 6)+
    theme(strip.text = element_text(size = 5)) +
    theme_bw()
  p_G1_t_mean
  
  p_cell_count_dose_response <- ggplot(df_mean_select, aes(x = Drug1ConcentrationRank, y = cell_count_norm_control, color = hours, group = hours)) +
    geom_path() +
    scale_color_manual(values = rank_colors) +
    labs(title = "Dose response curves for cell count") +
    xlab("Drug concentration") +
    ylab("Cell count (normalized to control)") +   
    guides(color = guide_legend("Hours")) +
    theme_bw()+
    facet_wrap(~factor(drugs), ncol = 4)
  p_cell_count_dose_response
  
  #replace drug rank with concentration
  p_cell_count_dose_response_conc <- ggplot(df_mean_select, aes(x = Drug1Concentration, y = cell_count_norm_control, color = hours, group = hours)) +
    geom_path() +
    scale_color_manual(values = rank_colors) +
    labs(title = "Dose response curves for cell count") +
    xlab("Drug concentration") +
    ylab("Cell count (normalized to control)") +   
    guides(color = guide_legend("Hours")) +
    theme_bw()+
    theme(axis.text.x = element_text(angle = 0))+
    facet_wrap(~factor(drugs), ncol = 4, scales = "free_x")
  p_cell_count_dose_response_conc
  
  plot_path <- paste0(data_path,plateID,"/Analysis/",pipeline_name,"/plots/")
  if(!dir.exists(plot_path)) dir.create(plot_path)
  
  pdf(paste0(plot_path,plateID,"_QA.pdf"), width = 10, height = 14)
  print(p_n)
  print(p_n_T0)
  print(p_cyto_CC_ratio)
  res <- dev.off()
  
  pdf(paste0(plot_path, plateID,"_summary.pdf"), width = 10, height = 7)
  print(p_n_t_T0_mean)
  print(p_G1_t_mean)
  print(p_cell_count_dose_response)
  print(p_cell_count_dose_response_conc)
  res <- dev.off()
}

```



```{r visualize_data}

  # #filter out low quality data
  # QA_evaluations <- map(plateIDs, get_QA_data) %>%
  #   bind_rows()
  # datasets <- list(l2 = NULL)
  # if(!length(QA_evaluations)==0){
  #   datasets$l2<- raw_datasets$l2 %>%
  #     anti_join(QA_evaluations, by = c("plateID", "well", "field"))
  # } else {
  #   datasets$l2<- raw_datasets$l2
  # }
  
 
##########
data_path <-  "/home/exacloud/gscratch/HeiserLab/images/"
pipeline_name <- "CtnK"
plateIDs <- c("2100601" = "2100601")
plateIDs <- c("HC00701" = "HC00701","HC00801" = "HC00801","HC00901" = "HC00901","HC01001" = "HC01001","HC01301" = "HC01301","HC01401" = "HC01401")
#plateIDs <- c("HC00801" = "HC00801","HC01001" = "HC01001","HC01401" = "HC01401")
#plateIDs <- c("HC01401" = "HC01401")

datasets <- map(plateIDs, create_level_2_data, data_path = data_path, pipeline_name = "CtnK")
res <- map(plateIDs, generate_l2_plots)

```
