---
title: "AU565 drug combination responses"
output:
  html_document: null
  pdf_document: default
  code_folding: hide
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(RColorBrewer)
library(readxl)

```

```{r functions}
get_l2_data <- function(plateID, data_path, pipeline_name = "PI"){
  level_2_data_path <- paste0(data_path, plateID, "/Analysis/",pipeline_name,"/",plateID,"_level_2.csv")
  l2 <- read_csv(level_2_data_path,
                col_types = cols(.default = "c",
                                    well = col_character(),
                                    field = col_double(),
                                    n_0 = col_double(),
                                    elapsed_minutes = col_double(),
                                    n = col_double(),
                                    Drug1Concentration = col_character(),
                                    Nuclei_PI_CC_mean_intensity = col_double(),
                                    Cyto_PI_CC_mean_intensity = col_double(),
                                    Cell_PI_CC_mean_intensity_ratio = col_double(),
                                    Cell_PI_CC_max_intensity_ratio = col_double(),
                                    Cell_PI_CC_min_intensity_ratio = col_double(),
                                    cell_count_norm_T0 = col_double(),
                                    G1_proportion = col_double()
                   )) %>%
    mutate(treatment = factor(treatment, levels = treatment_levels, ordered = TRUE),
           plateID = plateID)
  return(l2)
}

```


```{r get_data}

data_path <- "/home/exacloud/gscratch/HeiserLab/images/"
pipeline_name <- "PI"
plateIDs <- c("AU01501","AU01601","AU01701","AU01702","AU01801","AU01802","AU01901","AU01902","AU02001","AU02002","AU02101","AU02301","AU02401", "AU02501")

treatment_levels = c("vehicle",
                     "control",
                     "Lapatinib_25", "Lapatinib_50", "Lapatinib_100", "Lapatinib_250",
                     
                     "Palbociclib_25", "Palbociclib_50", "Palbociclib_100",  "Palbociclib_250" ,
                     "Gemcitabine_5", "Gemcitabine_10", "Gemcitabine_17", "Gemcitabine_30",
                     "Gemcitabine_100",
                     "Palbociclib_25_Gemcitabine_10",
                     "Palbociclib_100_Gemcitabine_10",
                     "Palbociclib_250_Gemcitabine_10",
                     "Doxorubicin_20",
                     "Palbociclib_50_Doxorubicin_20",
                     "Lapatinib_100_Doxorubicin_20",
                     "Paclitaxel_2",
                     "Paclitaxel_2_Lapatinib_100",
                     "Paclitaxel_2_Doxorubicin_20",
                     "Paclitaxel_2_Palbociclib_50",
                     "Paclitaxel_2_Gemcitabine_10",
                     "BEZ235_1", "BEZ235_2.5", "BEZ235_5", "BEZ235_10", "BEZ235_20", "BEZ235_30", "BEZ235_50",
                     "Cabozantinib_50", "Cabozantinib_100",  "Cabozantinib_250", "Cabozantinib_500", "Cabozantinib_1000", "Cabozantinib_2500", "Cabozantinib_5000",
                     "Trametinib_50", "Trametinib_100", "Trametinib_250", "Trametinib_500", "Trametinib_1000", 
                     "Trametinib_2500", "Trametinib_5000",
                     "5FU_125", "5FU_250", "5FU_400", "5FU_550", "5FU_750", "5FU_1000", "5FU_2500", 
                     "AZD5438_50", "AZD5438_100", "AZD5438_250","AZD5438_500", "AZD5438_1000", "AZD5438_2500", "AZD5438_5000",
                     "Panobinostat.5", "Panobinostat_1", "Panobinostat_2.5", "Panobinostat_5" , "Panobinostat_6.5" ,  "Panobinostat_10", "Panobinostat_12.5",
                     "JQ1_50",  "JQ1_100", "JQ1_250", "JQ1_500", "JQ1_1000", "JQ1_2500", "JQ1_5000",
                     "Bortezomib_1",  "Bortezomib_2.5", "Bortezomib_5", "Bortezomib_10", "Bortezomib_20", "Bortezomib_30", "Bortezomib_50", 
                     "MK1775_50", "MK1775_100", "MK1775_175","MK1775_275", "MK1775_375", "MK1775_500", "MK1775_700",
                     "MG132_1", "MG132_2.5","MG132_5","MG132_10","MG132_20","MG132_30","MG132_50",
                     "Everolimus_50","Everolimus_100","Everolimus_250","Everolimus_500","Everolimus_1000","Everolimus_2500","Everolimus_5000")

cols <- c("BEZ235_1" = "cornflowerblue", "Cabozantinib_50" = "cornflowerblue", "Trametinib_50" = "cornflowerblue",
          "BEZ235_2.5" = "darkcyan", "Cabozantinib_100" = "darkcyan","Trametinib_100" = "darkcyan",
          "BEZ235_5" = "cadetblue4",   "Cabozantinib_250" = "cadetblue4", "Trametinib_250" = "cadetblue4",
          "BEZ235_10" = "cadetblue", "Cabozantinib_500" = "cadetblue",  "Trametinib_500" = "cadetblue", 
          "BEZ235_20" = "blue",  "Cabozantinib_1000" = "blue", "Trametinib_1000" = "blue",
          "BEZ235_30" = "blue3",  "Cabozantinib_2500" = "blue3", "Trametinib_2500" = "blue3",
          "BEZ235_50" = "darkblue", "Cabozantinib_5000" = "darkblue", "Trametinib_5000" = "darkblue",
          "5FU_125" = "cornflowerblue", "5FU_250"= "darkcyan", "5FU_400" = "cadetblue4", "5FU_550" = "cadetblue",
          "5FU_750" = "blue", "5FU_1000" = "blue3", "5FU_2500" = "darkblue", 
          "AZD5438_50"= "cornflowerblue", "AZD5438_100"= "darkcyan", "AZD5438_250" = "cadetblue4",
          "AZD5438_500" = "cadetblue", "AZD5438_1000" = "blue", "AZD5438_2500" = "blue3",
          "AZD5438_5000" = "darkblue",
          "Bortezomib_1" = "cornflowerblue", "Bortezomib_2.5"= "darkcyan", "Bortezomib_5" = "cadetblue4",
          "Bortezomib_10" = "cadetblue","Bortezomib_20" = "blue", "Bortezomib_30" = "blue3","Bortezomib_50" = "darkblue",
          "Panobinostat.5"= "cornflowerblue", "Panobinostat_1"= "darkcyan", "Panobinostat_2.5" = "cadetblue4",
          "Panobinostat_5" = "cadetblue", "Panobinostat_6.5"  = "blue",  "Panobinostat_10" = "blue3",
          "Panobinostat_12.5" = "darkblue",
          "JQ1_50" = "cornflowerblue", "JQ1_100"= "darkcyan", "JQ1_250" = "cadetblue4", "JQ1_500" = "cadetblue",
          "JQ1_1000" = "blue", "JQ1_2500" = "blue3", "JQ1_5000" = "darkblue", 
          "MK1775_50" = "cornflowerblue", "MK1775_100"= "darkcyan", "MK1775_175" = "cadetblue4", "MK1775_275" = "cadetblue",
          "MK1775_375" = "blue", "MK1775_500" = "blue3", "MK1775_700" = "darkblue",
          "MG132_1" = "cornflowerblue", "MG132_2.5" = "darkcyan", "MG132_5" = "cadetblue4","MG132_10" = "cadetblue",
          "MG132_20" = "blue", "MG132_30" = "blue3", "MG132_50" = "darkblue",
          "Everolimus_50" = "cornflowerblue", "Everolimus_100"= "darkcyan", "Everolimus_250" = "cadetblue4",
          "Everolimus_500" = "cadetblue", "Everolimus_1000" = "blue", "Everolimus_2500" = "blue3",
          "Everolimus_5000" = "darkblue")



l2 <- map(plateIDs, get_l2_data, data_path = data_path) %>%
  bind_rows() %>%
  filter(!(plateID == "AU01801" & drugs %in% c("Bortezomib", "MK1775")))

write_csv(l2, "../tables/AU565_round2and3_level2.csv")

l2_model_subset <- l2 %>%
    mutate(treatment = paste0(Drug1, "_", Drug1Concentration)) %>%
  select(plateID, well, field, elapsed_minutes, treatment, n, n_0, cell_count_norm_T0, G1_proportion) %>%
  rename(cell_count = n,
         cell_count_T0 = n_0) %>%
    mutate(treatment = case_when(treatment == "vehicle" ~ "control",
                               TRUE ~ as.character(treatment)),
           cell_count_norm_T0 = round(cell_count_norm_T0, digits = 3),
            G1_proportion = round(G1_proportion, digits = 3))
write_csv(l2_model_subset, "../tables/AU565_round2and3_model_subset_level2.csv")

l2_summary <- l2 %>% 
  mutate(
         drugs = case_when(drugs == "vehicle" ~ "control",
                               TRUE ~ drugs)) %>%
  group_by(drugs) %>%
  summarise(Cells_quantifed = sum(n))

#Combine the fields in each well at each time point
l2_plate_mean <- l2 %>%
  mutate(treatment = case_when(treatment == "vehicle" ~ factor("control",levels = treatment_levels,ordered = TRUE),
                               TRUE ~ factor(treatment,levels = treatment_levels,ordered = TRUE)),
         drugs = case_when(drugs == "vehicle" ~ "control",
                               TRUE ~ drugs),
         Drug1 = case_when(Drug1 == "vehicle" ~ "control",
                               TRUE ~ Drug1)) %>%
  group_by(plateID, well, treatment, elapsed_minutes, Drug1, Drug1Concentration, drugs) %>%
  summarise(n = mean(n),
            cell_count_norm_T0 = mean(cell_count_norm_T0),
            G1_proportion= mean(G1_proportion),
            .groups = "drop")

```

```{r combined_cell_counts, fig.width=5, fig.height=14, eval = FALSE}

p_n_m_rep <- ggplot(l2_plate_mean, aes(x = elapsed_minutes, y = cell_count_norm_T0, color = plateID, group = interaction(plateID, well))) +
  geom_path() +
  scale_y_continuous(trans = 'log2') +
  labs(title = "Cell counts for all treatments (T0 normed)",
       subtitle = "organized by treatment and dosage (uM)",
  xlab ="minutes",
       ylab = "cell count (log2 spacing)") +
  guides(color = guide_legend(ncol = 1)) +
  facet_grid(Drug1Concentration~drugs)+
  theme(strip.text = element_text(size = 5)) +
  theme_bw()
p_n_m_rep

```

```{r combined_dose_response, fig.width=8, fig.height=6}
#Combine plates to get a single response for each concentration

l2_control_mean <- l2_plate_mean %>%
  filter(treatment %in% c("control", "vehicle")) %>%
  group_by(treatment, elapsed_minutes, Drug1, Drug1Concentration, drugs) %>%
  summarise(n = mean(n),
            cell_count_norm_T0 = mean(cell_count_norm_T0),
            G1_proportion= mean(G1_proportion),
            .groups = "drop") %>%
  mutate(elapsed_hours = elapsed_minutes/60) %>%
  select(elapsed_hours, cell_count_norm_T0, G1_proportion) %>%
  rename(control_cell_count_norm_T0 = cell_count_norm_T0,
         control_G1_proportion = G1_proportion)

l2_mean <- l2_plate_mean %>%
  filter(!treatment %in% c("control", "vehicle")) %>%
  group_by(treatment, elapsed_minutes, Drug1, Drug1Concentration, drugs) %>%
  summarise(n = mean(n),
            cell_count_norm_T0 = mean(cell_count_norm_T0),
            G1_proportion= mean(G1_proportion),
            .groups = "drop") %>%
  mutate(elapsed_hours = elapsed_minutes/60) %>%
  left_join(l2_control_mean, by = "elapsed_hours")


p_n_m_rep <- ggplot(l2_mean, aes(x = elapsed_hours, y = cell_count_norm_T0, color = treatment, group = interaction(Drug1Concentration))) +
  geom_path() +
  geom_path(aes(y = control_cell_count_norm_T0), color = "red")+
  scale_y_continuous(trans = 'log2') +
  scale_x_continuous(breaks = c(0,24, 48, 72, 96))+
  scale_color_manual(values = cols) +
  labs(title = "Cell counts for all treatments (T0 normed)",
       subtitle = "organized by treatment and dosage, control in red") +
  xlab("hours") +
  ylab("relative cell count (log2 spacing)") +
  guides(color ="none") +
  facet_wrap(~drugs)+
  theme(strip.text = element_text(size = 5)) +
  theme_bw()
p_n_m_rep

p_n_m_rep_free <- ggplot(l2_mean, aes(x = elapsed_hours, y = cell_count_norm_T0, color = treatment, group = interaction(Drug1Concentration))) +
  geom_path() +
  geom_path(aes(y = control_cell_count_norm_T0), color = "red")+
  scale_y_continuous(trans = 'log2') +
  scale_x_continuous(breaks = c(0,24, 48, 72, 96))+
  scale_color_manual(values = cols) +
  labs(title = "Cell counts for all treatments (T0 normed)",
       subtitle = "organized by treatment and dosage, control in red, y scale varies") +
  xlab("hours") +
  ylab("relative cell count (log2 spacing)") +
  guides(color ="none") +
  facet_wrap(~drugs,scales = "free_y")+
  theme(strip.text = element_text(size = 5)) +
  theme_bw()
p_n_m_rep_free


p_G1_m_rep <- ggplot(l2_mean, aes(x = elapsed_hours, y = G1_proportion, color = treatment, group = interaction(Drug1Concentration))) +
  geom_path() +
  geom_path(aes(y = control_G1_proportion), color = "red")+
  scale_x_continuous(breaks = c(0,24, 48, 72, 96))+
  scale_color_manual(values = cols) +
  labs(title = "G1 proportion for all treatments",
       subtitle = "organized by treatment and dosage, control in red") +
  xlab("hours") +
  ylab("G1 proportion") +
  guides(color ="none") +
  facet_wrap(~drugs)+
  theme(strip.text = element_text(size = 5)) +
  theme_bw()
p_G1_m_rep

```

