---
title: "Live cell imaging field-level responses"
output: 
  html_document:
  code_folding: hide
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(viridis)
library(readxl)
library(ComplexHeatmap)
library(rrscale)

```


```{r get_data}

IF_values <- read_csv("IF/Data/MDD_IF_Level4.csv") %>%
  rename(feature = X1) %>%
  gather(key = "condition_collection", value = "value", -feature) %>%
  filter(str_detect(feature, selected_IF_features_regex)) %>%
  mutate(collection = str_remove(condition_collection, ".*_"),
         ligand = str_remove(condition_collection, "_.*"),
         experimentalTimePoint = str_extract(condition_collection, "_.*_"),
         experimentalTimePoint = str_remove_all(experimentalTimePoint,"_"),
         experimentalTimePoint = as.numeric(experimentalTimePoint),
         value = as.numeric(value),
         Type = "IF",
         feature = paste0(feature, "_IF")) %>%
  filter(!feature %in% c("collection_IF", "conditionName_IF","experimentalTimePoint_IF", "ligand_IF")) %>%
  dplyr::select(-condition_collection) %>%
  group_by(feature, ligand, experimentalTimePoint, Type) %>%
  summarise(value = median(value, na.rm = TRUE)) %>%
  ungroup()


  IF_values_rr <- IF_values %>%
    group_by(feature) %>%
    mutate(value = rrscaleValues(value, zeros = 0.01, zscore_cutoff = Inf)[["RR"]]) %>%
    ungroup()

  
plateIDs <- c("HC00701","HC00801","HC00901","HC01001")

l2 <- map_dfr(plateIDs, get_level_2_data)

  
feature_treatment_hourly_df <- l2 %>%
    filter(!grepl("30m" ,time_slice)) 

feature_treatment_hourly_m <- feature_treatment_hourly_df %>%
  select(matches("Cell_|Cyto_|Nuclei|^G1|Neighborhood") , -cell_cycle_state_threshold) %>%
  as.matrix()
rownames(feature_treatment_hourly_m) <- paste0(feature_treatment_hourly_df$treatment, "_", feature_treatment_hourly_df$elapsed_minutes)

feature_treatment_hourly_m_hm <- Heatmap(feature_treatment_hourly_m)

feature_treatment_hm

feature_treatment_subset_df <- l2 %>%
    filter(elapsed_minutes %in% seq(300, 5760, 300) )

feature_treatment_subset_m <- feature_treatment_subset_df %>%
  select(matches("Cell_|Cyto_|Nuclei|^G1|Neighborhood") , -cell_cycle_state_threshold) %>%
  as.matrix()
rownames(feature_treatment_subset_m) <- paste0(feature_treatment_subset_df$treatment, "_", feature_treatment_subset_df$elapsed_minutes)

feature_treatment_subset_m_hm <- Heatmap(feature_treatment_subset_m)

feature_treatment_subset_m_hm

generate_l2_plots <- function(plateID){
  l2_data_path <- paste0(data_path,plateID,"/Analysis/",pipeline_name,"/",plateID,"_level_2.csv")
  
  df <- datasets[[plateID]]
  
    #dynamically assign consistent colors to the dosage concentrations
  treatments <-df$treatment%>%
    unique()  %>%
    str_sort(numeric = TRUE)
  idx <- which(treatments %in% c("control","vehicle","Untreated")) # Positions of Untreated in df$treatement
  treatments <- treatments[-idx]
  treatments_colors <-  rep(viridis(7, direction = -1), length.out = length(treatments))
  names(treatments_colors) <- treatments
  cols <- c("control"="royalblue","vehicle"="royalblue","Untreated"="royalblue", treatments_colors)
  
  p_n <- ggplot(df, aes(x = elapsed_minutes, y = n, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
    scale_y_continuous(trans = 'log2')+
    labs(title = "Cell counts in each field",
         subtitle = "organized by position in the plate",
         xlab ="minutes",
         ylab = "cell count (log2 spacing)") +
    facet_wrap(~well, ncol = 6)
  p_n
  
  p_n_T0 <- ggplot(df, aes(x = elapsed_minutes, y = cell_count_norm_T0, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
    scale_y_continuous(trans = 'log2') +
    labs(title = "Cell counts in each field (T0 normed)",
         subtitle = "organized by position in the plate",
         xlab ="minutes",
         ylab = "cell count (log2 spacing)") +
    facet_wrap(~well, ncol = 6)
  p_n_T0
  
  p_CC <- ggplot(df, aes(x = elapsed_minutes, y = Nuclei_CKn_CC_mean_intensity, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
    labs(title = "Cell cycle intensity in the nuclei, mean",
         xlab = "minutes",
         ylab = "intensity") +
    facet_wrap(~well, ncol = 6)
  p_CC
  

  p_cyto_CC <- ggplot(df, aes(x = elapsed_minutes, y = Cyto_CKn_CC_mean_intensity, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
    labs(title = "Cell cycle intensity in the cytoplasm, mean",
         xlab = "minutes",
         ylab = "intensity") +
    facet_wrap(~well, ncol = 6)
  p_cyto_CC
  
  p_cyto_CC_ratio <- ggplot(df, aes(x = elapsed_minutes, y = Cell_CKn_CC_mean_intensity_ratio, color = factor(field))) +
    geom_path() +
    stat_summary(fun=mean, aes(group=1), geom="line", colour="blue") +
    labs(title = "Cell cycle intensity in the cytoplasm/nuclei, mean",
         xlab = "minutes",
         ylab = "intensity") +
    facet_wrap(~well, ncol = 2)
  p_cyto_CC_ratio
  
  #summarize each well and group plots by drug
  df_control_mean <- df %>%
    filter(treatment %in% c("vehicle", "control", "Untreated")) %>%
    group_by(elapsed_minutes) %>%
    summarise(cell_count_norm_T0_control = mean(cell_count_norm_T0),
              n_control = mean(n),
              G1_proportion_control = mean(G1_proportion),
               .groups = "drop")
  
  df_mean <- df %>%
    filter(!treatment %in% c("vehicle", "control", "Untreated")) %>%
    mutate(treatment = fct_drop(treatment)) %>%
    group_by(elapsed_minutes, treatment, drugs, Drug1Concentration) %>%
    summarise(cell_count_norm_T0 = mean(cell_count_norm_T0),
              n = mean(n),
              G1_proportion = mean(G1_proportion), .groups = "drop") %>%
    left_join(df_control_mean, by = "elapsed_minutes")
  
  p_n_t_T0_mean <- ggplot(df_mean, aes(x = elapsed_minutes, y = cell_count_norm_T0, color = treatment, group = Drug1Concentration)) +
    geom_path() +
    geom_path(aes(y = cell_count_norm_T0_control), color = "firebrick4")+
    scale_y_continuous(trans = 'log2') +
    scale_color_manual(values = cols) +
    labs(title = "Cell counts for each treatment (T0 normed)",
         subtitle = "organized by treatment and dosage",
         xlab ="minutes",
         ylab = "cell count (log2 spacing)") +
    guides(color = "none") +
    facet_wrap(~drugs, ncol = 6)+
    theme(strip.text = element_text(size = 5)) +
    theme_bw()
  p_n_t_T0_mean
  
  p_G1_t_mean <- ggplot(df_mean, aes(x = elapsed_minutes, y = G1_proportion, color = treatment, group = Drug1Concentration)) +
    geom_path() +
        geom_path(aes(y = G1_proportion_control), color = "firebrick4")+
    scale_color_manual(values = cols) +
    labs(title = "G1 proportion for each treatment",
         subtitle = "organized by treatment and dosage",
         xlab ="minutes",
         ylab = "G1 proportion") +
    guides(color = "none") +
    facet_wrap(~drugs, ncol = 6)+
    theme(strip.text = element_text(size = 5)) +
    theme_bw()
  p_G1_t_mean
  
  
  #look at density plots of the cell cycle ratios per image
  #start with just the initial time point
  # earliest_time_point <- unique(l2$elapsed_minutes) %>%
  #     min() 
  # time_interval <- 1440
  # unique_timepoints <- unique(l2$elapsed_minutes)
  # selected_timepoints <- time_interval*as.integer(unique_timepoints/time_interval) %>%
  #   unique()
  # 
  # df <- l1 %>%
  #   filter(elapsed_minutes %in% selected_timepoints) %>%
  #   mutate(elapsed_hours = as.integer(elapsed_minutes)/60)
  # 
  # p_densities <- ggplot(df, aes(Cell_CKn_CC_mean_intensity_ratio, fill = treatment, color = treatment)) +
  #   geom_density(alpha = .2)+
  #         scale_color_manual(values = cols) +
  #             scale_fill_manual(values = cols) +
  #   geom_vline(xintercept = g1_threshold)+
  #   facet_grid(elapsed_hours~drugs) +
  #   guides(fill = "none", color = "none") +
  #   theme_bw()
  # p_densities
  
  plot_path <- paste0(data_path,plateID,"/Analysis/",pipeline_name,"/plots/")
  if(!dir.exists(plot_path)) dir.create(plot_path)
  
  pdf(paste0(plot_path,plateID,"_QA.pdf"), width = 10, height = 14)
  print(p_n)
  print(p_n_T0)
  print(p_cyto_CC_ratio)
  print(p_CC)
  print(p_cyto_CC)
  res <- dev.off()
  
  pdf(paste0(plot_path, plateID,"_summary.pdf"), width = 10, height = 7)
  print(p_n_t_T0_mean)
  print(p_G1_t_mean)
  res <- dev.off()
}

```



```{r visualize_data}

  # #filter out low quality data
  # QA_evaluations <- map(plateIDs, get_QA_data) %>%
  #   bind_rows()
  # datasets <- list(l2 = NULL)
  # if(!length(QA_evaluations)==0){
  #   datasets$l2<- raw_datasets$l2 %>%
  #     anti_join(QA_evaluations, by = c("plateID", "well", "field"))
  # } else {
  #   datasets$l2<- raw_datasets$l2
  # }
  
 
##########
data_path <-  "/home/exacloud/gscratch/HeiserLab/images/"
pipeline_name <- "CKn"
plateIDs <- c("AU00601" = "AU00601")

datasets <- map(plateIDs, create_level_2_data, data_path = data_path)
res <- map(plateIDs, generate_l2_plots)


```
